#!/bin/bash

# This script is for managing filebrowser container
# Usage:
#   to start container, "./run start"
#   to stop container, "./run stop"

source /etc/environment

filebrowser="${DOCKERDIR}/filebrowser"

# The script will ask required things if filebrowser has not been configured yet
if ! docker network ls | grep filebrowser &>/dev/null ; then
    docker network create -o "com.docker.network.bridge.enable_icc"="false" filebrowser &>/dev/null
    read -rp "Enter domain name for filebrowser: " domain
    sed -i "s/change_domain/$domain/g" ${filebrowser}/filebrowser.nginx
    cp ${filebrowser}/filebrowser.nginx ${DOCKERDIR}/nginx/conf.d/filebrowser.conf
fi

# The container will be started if the first argument is "start"
[[ "$1" == "start" ]] \
    && docker-compose -f ${filebrowser}/docker-compose.yml pull \
    && docker-compose -f ${filebrowser}/docker-compose.yml up -d

# The container will be stopped if the first argument is "stop"
[[ "$1" == "stop" ]] \
    && docker-compose -f ${filebrowser}/docker-compose.yml down

exit 0
