#!/bin/bash

# This script is for managing rustpad container
# Usage:
#   to start container, "./run start"
#   to stop container, "./run stop"

source /etc/environment

rustpad="${DOCKERDIR}/rustpad"

# The script will ask required things if rustpad has not been configured yet
if ! docker network ls | grep rustpad &>/dev/null ; then
    docker network create -o "com.docker.network.bridge.enable_icc"="false" rustpad &>/dev/null
    read -rp "Enter domain name for rustpad: " domain
    sed -i "s/change_domain/$domain/g" ${rustpad}/rustpad.nginx
    cp ${rustpad}/rustpad.nginx ${DOCKERDIR}/nginx/conf.d/rustpad.conf
fi

# The container will be started if the first argument is "start"
[[ "$1" == "start" ]] \
    && docker-compose -f ${rustpad}/docker-compose.yml pull \
    && docker-compose -f ${rustpad}/docker-compose.yml up -d

# The container will be stopped if the first argument is "stop"
[[ "$1" == "stop" ]] \
    && docker-compose -f ${rustpad}/docker-compose.yml down

exit 0
