version: "3"
services:
  ipsecvpn:
    image: hwdsl2/ipsec-vpn-server:latest
    container_name: ipsecvpn
    env_file:
      - ./ipsecvpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - ./ikev2:/etc/ipsec.d
    privileged: true
    hostname: ipsec
    restart: unless-stopped
networks:
  default:
    external:
      name: ipsecvpn
