#!/bin/bash

# This script is for managing ipsecvpn container
# Usage:
#   to start container, "./run start"
#   to stop container, "./run stop"

source /etc/environment

ipsecvpn="${DOCKERDIR}/ipsecvpn"

# The script will ask required things if ipsecvpn has not been configured yet
if ! docker network ls | grep ipsecvpn &>/dev/null ; then
    docker network create -o "com.docker.network.bridge.enable_icc"="false" ipsecvpn &>/dev/null
    mkdir ${ipsecvpn}/ikev2
    read -rp "Enter preshared key for ipsecvpn: " psk
    read -rp "Enter domain name for ipsecvpn: " domain
    sed -i "s/change_psk/$psk/g" ${ipsecvpn}/ipsecvpn.env
    sed -i "s/change_domain/$domain/g" ${ipsecvpn}/ipsecvpn.env
fi

# The container will be started if the first argument is "start"
[[ "$1" == "start" ]] \
    && docker-compose -f ${ipsecvpn}/docker-compose.yml pull \
    && docker-compose -f ${ipsecvpn}/docker-compose.yml up -d

# The container will be stopped if the first argument is "stop"
[[ "$1" == "stop" ]] \
    && docker-compose -f ${ipsecvpn}/docker-compose.yml down

exit 0
