version: "3"
services:
  coturn_secret:
    image: coturn/coturn:alpine
    container_name: coturn_secret
    network_mode: host
    volumes:
      - ./fullchain.pem:/var/lib/turn/fullchain.pem:ro
      - ./key.pem:/var/lib/turn/key.pem:ro
      - ./turn_with_secret.conf:/etc/coturn/turnserver.conf
    restart:  unless-stopped
  coturn_password:
    image: coturn/coturn:alpine
    container_name: coturn_password
    network_mode: host
    volumes:
      - ./fullchain.pem:/var/lib/turn/fullchain.pem:ro
      - ./key.pem:/var/lib/turn/key.pem:ro
      - ./turn_with_password.conf:/etc/coturn/turnserver.conf
    restart:  unless-stopped
