version: "3"
services:
  rustdesk_hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk_hbbs
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"
    volumes:
      - ./hbbs:/root
    command: hbbs -r change_domain:21117
    depends_on:
      - rustdesk_hbbr
    restart: unless-stopped
  rustdesk_hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk_hbbr
    ports:
      - "21117:21117"
      - "21119:21119"
    volumes:
      - ./hbbr:/root
    command: hbbr
    restart: unless-stopped
networks:
  default:
    external:
      name: rustdesk
