version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./www:/usr/share/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart:  unless-stopped