#!/bin/bash

# This script is for managing kms container
# Usage:
#   to start container, "./run start"
#   to stop container, "./run stop"

source /etc/environment

kms="${DOCKERDIR}/kms"

# The script will ask required things if kms has not been configured yet
if ! docker network ls | grep kms &>/dev/null ; then
    docker network create -o "com.docker.network.bridge.enable_icc"="false" kms &>/dev/null
    tar -xf ${DOCKERDIR}/nginx/www/kms.tar.gz -C ${DOCKERDIR}/nginx/www/
    read -rp "Enter domain name for kms: " domain
    sed -i "s/change_domain/$domain/g" ${kms}/kms.nginx
    cp ${kms}/kms.nginx ${DOCKERDIR}/nginx/conf.d/kms.conf
fi

# The container will be started if the first argument is "start"
[[ "$1" == "start" ]] \
    && docker-compose -f ${kms}/docker-compose.yml pull \
    && docker-compose -f ${kms}/docker-compose.yml up -d

# The container will be stopped if the first argument is "stop"
[[ "$1" == "stop" ]] \
    && docker-compose -f ${kms}/docker-compose.yml down

exit 0
